import assert from "node:assert/strict";
import test from "node:test";

test("AC-005/TST012-AC-004/TST014-AC-003: the Core package root exposes only the public contract", async () => {
  const core = await import("@praxisbound/core");

  assert.deepEqual(Object.keys(core).sort(), [
    "IMPLEMENTED_PROTOCOL_VERSION",
    "RESULT_SCHEMA_VERSION",
    "ResultEnvelopeValidationError",
    "SUPPORTED_PROTOCOL_RANGE",
    "activationAdoptionPath",
    "activationDestinations",
    "activationDirectories",
    "activationSkillDirectory",
    "activationSnapshotPath",
    "adoptionMarkerPath",
    "adoptionNextSteps",
    "assertResultEnvelope",
    "createAdoptionMarker",
    "evaluateActivationAcquisition",
    "evaluateActivationMutation",
    "evaluateActivationScratchCleanup",
    "evaluateHandoff",
    "evaluateInitMutation",
    "evaluateReleaseReadiness",
    "evaluateRepositoryDoctor",
    "evaluateStoryContract",
    "evaluateStoryReadiness",
    "evaluateVerificationResult",
    "findActivationPreconditionMismatches",
    "findInitPreconditionMismatches",
    "getActivationObservationScope",
    "getInitObservationScope",
    "getToolingCapabilities",
    "indexReviewBatch",
    "legacyActivationDestinations",
    "legacyActivationSkillDirectory",
    "legacyActivationSnapshotPath",
    "planActivation",
    "planMutation",
    "planReviewBatch",
    "posixCksum",
    "readStoryDecisions",
    "renderReviewProjection",
    "resolveProtocolSelector",
    "resolveVerificationPlan",
    "validateResultEnvelope",
  ]);
});
