import assert from "node:assert/strict";
import test from "node:test";

test("AC-005/TST012-AC-004/TST014-AC-003: the Core package root exposes only the public contract", async () => {
  const core = await import("@praxisbound/core");

  assert.deepEqual(Object.keys(core).sort(), [
    "GOAL_PLAN_MANIFEST_SCHEMA_VERSION",
    "IMPLEMENTED_PROTOCOL_VERSION",
    "PLAN_COVERAGE_REVIEW_SCHEMA_VERSION",
    "RESULT_SCHEMA_VERSION",
    "ResultEnvelopeValidationError",
    "SUPPORTED_PROTOCOL_RANGE",
    "activationAdoptionPath",
    "activationDestinations",
    "activationDirectories",
    "activationSkillDirectory",
    "activationSnapshotPath",
    "adoptionMarkerPath",
    "adoptionNextSteps",
    "assertResultEnvelope",
    "buildTargetLookup",
    "compareUtf8",
    "createAdoptionMarker",
    "dedupeRevisions",
    "escapeHiddenCharacters",
    "evaluateActivationAcquisition",
    "evaluateActivationMutation",
    "evaluateActivationScratchCleanup",
    "evaluateHandoff",
    "evaluateInitMutation",
    "evaluateReleaseReadiness",
    "evaluateRepositoryDoctor",
    "evaluateStoryContract",
    "evaluateStoryReadiness",
    "evaluateVerificationResult",
    "exportGoalPlanManifest",
    "exportPlanCoverageReview",
    "findActivationPreconditionMismatches",
    "findInitPreconditionMismatches",
    "getActivationObservationScope",
    "getInitObservationScope",
    "getToolingCapabilities",
    "indexReviewBatch",
    "isHiddenOrReorderingCodePoint",
    "isSyntacticallySafeRepoPath",
    "jsonParseFailureMessage",
    "legacyActivationDestinations",
    "legacyActivationSkillDirectory",
    "legacyActivationSnapshotPath",
    "matchRevisionTarget",
    "parseRevisionResponses",
    "parseRevisionSheetBlock",
    "planActivation",
    "planMutation",
    "planReviewBatch",
    "posixCksum",
    "rawJsonMaxDepth",
    "readStoryDecisions",
    "renderReviewProjection",
    "resolveProtocolSelector",
    "resolveVerificationPlan",
    "revisionContentKey",
    "sameRevisionContent",
    "sha256Hex",
    "supersedesConflicts",
    "validateGoalPlanManifest",
    "validatePlanCoverageReview",
    "validateResultEnvelope",
    "validateRevisionRecordSet",
    "validateStoredResponsesRecord",
    "validateStoredRevisionRecord",
  ]);
});
